require 'rake'
require 'rspec/core/rake_task'

desc 'Default: Run all the specs for rails 3'
task :default => :spec

desc 'Run all the specs for rails 3'
RSpec::Core::RakeTask.new(:spec) do |task|
  task.pattern = '**/*_spec.rb'
end
